import {NextPage} from "next";
import styles from '../styles/Home.module.css'

import Head from "next/head";
import Link from "next/link";
const Hello: NextPage = () => {
  return (
      <div className={styles.container}>
        <Head>
          <title>Hello World!</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <h1 className={styles.title}>
              Hello Page
            </h1>
            <p className={styles.description}>
                Say Hello to the world! <br/>
              Modify by editing <code className={styles.code}>pages/hello.tsx</code>
            </p>
            <div className={styles.grid}>
                <Link href={'/'}>
                    <div className={styles.card}>
                        <h2>&larr; Back Home</h2>
                        <p>Navigate back home</p>
                    </div>
                </Link>
            </div>
        </main>
      </div>
  );
}
export default Hello;

